# Template to produce a new OpenShift pipeline job for triggering a build on repotracker messages
#
---
apiVersion: v1
kind: Template
metadata:
  name: waiverdb-repotracker-trigger
labels:
  template: waiverdb-repotracker-trigger
parameters:
- name: NAME
  displayName: Short unique identifier for the templated instances
  description: This field is used to deploy multiple pipelines to one OpenShift project from this template.
  value: waiverdb-repotracker-trigger
- name: TRACKED_CONTAINER_REPO
  displayName: Container repo to be tracked
  value: "quay.io/factory2/waiverdb"
- name: TRACKED_TAG
  displayName: Name of tag to be tracked
  required: true
- name: JENKINS_AGENT_IMAGE
  displayName: Container image for Jenkins slave pods
  value: docker-registry.upshift.redhat.com/factory2/factory2-integration-test-jenkins-slave:latest
- name: OPENSHIFT_CLOUD_NAME
  displayName: Name of OpenShift cloud in Jenkins master configuration
  value: openshift
- name: PIPELINE_AS_A_SERVICE_BUILD_NAMESPACE
  displayName: The namespace where the Pipeline-as-a-Service project request BuildConfig has been defined
  required: false
  value: c3i
- name: MESSAGING_PROVIDER
  displayName: Name of the JMS messaging provider
  value: Red Hat UMB
- name: MESSAGING_TOPIC
  displayName: Name of the topic that the trigger subscribes to
  value: "Consumer.rh-jenkins-ci-plugin.c3i-waiverdb-repotracker-trigger.VirtualTopic.eng.repotracker.container.tag.>"
- name: ENVIRONMENT
  displayName: environment name (dev/stage/prod)
  required: true
  value: dev
- name: BACKEND_INTEGRATION_TEST_REPO
  displayName: backend integration test repo
  value: https://gitlab.cee.redhat.com/devops/factory2-segment-tests.git
- name: BACKEND_INTEGRATION_TEST_REPO_BRANCH
  displayName: backend integration test repo
  required: true
  value: master
- name: BACKEND_INTEGRATION_TEST_FILE
  displayName: backend integration test file
  required: true
  value: greenwave-segment-test/greenwave-segment-test-c3i.sh
- name: NO_CLEANUP_AFTER_TEST
  displayName: Keep environment after test
  value: "false"
- name: MAIL_ADDRESS
  displayName: If set, build failure messages to this mail address.
{% include "snippets/c3i-library-parameters.yaml" %}
objects:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: "${NAME}-jenkins-slave"
    labels:
      app: "${NAME}"
- kind: RoleBinding
  apiVersion: v1
  metadata:
    name: "${NAME}-jenkins-slave_edit"
    labels:
      app: "${NAME}"
  subjects:
  - kind: ServiceAccount
    name: "${NAME}-jenkins-slave"
  roleRef:
    name: edit
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  spec:
    runPolicy: "Serial"
    completionDeadlineSeconds: 1800
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        env:
        - name: "OPENSHIFT_CLOUD_NAME"
          value: "${OPENSHIFT_CLOUD_NAME}"
        - name: "JENKINS_AGENT_IMAGE"
          value:  "${JENKINS_AGENT_IMAGE}"
        - name: "JENKINS_AGENT_SERVICE_ACCOUNT"
          value: "${NAME}-jenkins-slave"
        - name: "TRACKED_CONTAINER_REPO"
          value: "${TRACKED_CONTAINER_REPO}"
        - name: "TRACKED_TAG"
          value: "${TRACKED_TAG}"
        - name: MESSAGING_PROVIDER
          value: "${MESSAGING_PROVIDER}"
        - name: MESSAGING_TOPIC
          value: "${MESSAGING_TOPIC}"
        - name: ENVIRONMENT
          value: "${ENVIRONMENT}"
        - name: PIPELINE_AS_A_SERVICE_BUILD_NAMESPACE
          value: "${PIPELINE_AS_A_SERVICE_BUILD_NAMESPACE}"
        - name: "NO_CLEANUP_AFTER_TEST"
          value: "${NO_CLEANUP_AFTER_TEST}"
        - name:  MAIL_ADDRESS
          value: "${MAIL_ADDRESS}"
        - name: BACKEND_INTEGRATION_TEST_REPO
          value: "${BACKEND_INTEGRATION_TEST_REPO}"
        - name: BACKEND_INTEGRATION_TEST_REPO_BRANCH
          value: "${BACKEND_INTEGRATION_TEST_REPO_BRANCH}"
        - name: BACKEND_INTEGRATION_TEST_FILE
          value: "${BACKEND_INTEGRATION_TEST_FILE}"
        # CI_MESSAGE and MESSAGE_HEADERS are used internally by JMS messaging plugin
        - name: CI_MESSAGE
          value:
        - name: MESSAGE_HEADERS
          value:
        jenkinsfile: |
          {% filter indent(width=10) %}{% include "waiverdb-repotracker-trigger.Jenkinsfile" %}{% endfilter %}
